name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.0
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Lint the project
        run: npm run lint
      - name: Build the project
        run: npm run build
        env:
          CI: true

  publish-npm:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: NPM
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.0
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
        env:
          CI: true
      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
